# Generated by Django 4.1.3 on 2022-11-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hinario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hinos',
            new_name='Hino',
        ),
    ]
